### ISSUE TITLE
seems to cause a dead lock

### ISSUE THREAD

**Issue by Jason210314** [skyzh/xv6-riscv-fall19#12]
在lock lab中，当前`bucket`中找不到时，需要从其他`bucket`中steal，过程中需要同时持有当前`bucket`和被steal的`bucket`的锁，当A steal from B，B steal from A时，可能会死锁，这种情况代表当前已经无`buf`可用，这种情况应当执行到结尾`panic`。

**Comment by skyzh** [comment]
这是一个已知问题，一直没有解决。您可以参见 https://github.com/skyzh/xv6-riscv-fall19/issues/10 的讨论。感觉可以在 steal 的时候上一把大锁解决这个问题。

**Comment by Jason210314** [comment]
> 这是一个已知问题，一直没有解决。您可以参见 #10 的讨论。感觉可以在 steal 的时候上一把大锁解决这个问题。

好的，多谢

**Comment by Jason210314** [comment]
> 这是一个已知问题，一直没有解决。您可以参见 #10 的讨论。感觉可以在 steal 的时候上一把大锁解决这个问题。

已经在自己实现里加了一把大锁解决了，感觉非常ugly。
